### PR TITLE
Add tidelift retriever basic test and functionality

### LINKED ISSUE #14: Write tidelift funding retriever
As suggested by John Speed. Like numfocus, I wonder if we'd only be able to retrieve a boolean "is it sponsored by tidelift or not" value

### PR DESCRIPTION
**Pull request by jspeed-meyers**
Fix #14 

Signed-off-by: John Speed Meyers <jsmeyers@chainguard.dev>

### CODE REVIEW

**Comment by jspeed-meyers** [comment]
@jmelot, the tests seem to pass, but there is an error with the linting, though it seems to be related to a CI issue, not the code itself. Can you make heads or tails of it?

Also, with this PR I've tried to bring the Tidelift retriever in line with the new schema and how the codebase implements it. Feedback is welcome. It is a Monday morning after all :)

**Comment by jspeed-meyers** [comment]
@jmelot, you are too good! Nice work identifying and fixing the issue.

**Review by jmelot — APPROVED** [review]
This looks good to me! My only small comment is that I wonder if it would be worth checking the links listed under "Sponsor this project" for tidelift projects (e.g. using this function https://github.com/georgetown-cset/funder-finder/blob/main/funderfinder/utils/github_sources.py#L26) as well as the text of the README.

**Comment by jspeed-meyers** [comment]
@jmelot - Agreed. I'll merge this plus open a new issue for exactly what you describe.

**Pull request merged**
